//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleTestAdapter.TestAdapter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleTestAdapter.TestAdapter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution test settings file could not be parsed, check file: {0}
        ///Exception: {1}.
        /// </summary>
        public static string CantParseSettings {
            get {
                return ResourceManager.GetString("CantParseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not attach debugger to process {0}:{1}{2}.
        /// </summary>
        public static string CouldNotAttachMessage {
            get {
                return ResourceManager.GetString("CouldNotAttachMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not attach debugger to process {0}, no error message available.
        /// </summary>
        public static string DebuggerAttachMessage {
            get {
                return ResourceManager.GetString("DebuggerAttachMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger attached to process {0}, took {1} ms.
        /// </summary>
        public static string DebuggerAttachTime {
            get {
                return ResourceManager.GetString("DebuggerAttachTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging is only possible if GoogleTestAdapter has been installed into Visual Studio - NuGet installation does not support this (and other features such as Visual Studio Options, toolbar, and solution settings)..
        /// </summary>
        public static string DebuggingMessage {
            get {
                return ResourceManager.GetString("DebuggingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match {1}.
        /// </summary>
        public static string DoesntMatch {
            get {
                return ResourceManager.GetString("DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (enable debug mode for more information).
        /// </summary>
        public static string EnableDebugMode {
            get {
                return ResourceManager.GetString("EnableDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors and warnings have occured during {0} {1}:{2}.
        /// </summary>
        public static string ErrorAndWarning {
            get {
                return ResourceManager.GetString("ErrorAndWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test case filter is invalid: {0}.
        /// </summary>
        public static string FilterInvalid {
            get {
                return ResourceManager.GetString("FilterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not identify Visual Studio version. {0} requires at least Visual Studio 2012 Update 1..
        /// </summary>
        public static string IdentifyVSError {
            get {
                return ResourceManager.GetString("IdentifyVSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches {1}.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There might be more information on the problem in Visual Studio&apos;s ActivityLog.xml (see e.g. https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/).
        /// </summary>
        public static string MoreInformationMessage {
            get {
                return ResourceManager.GetString("MoreInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test case filter provided.
        /// </summary>
        public static string NoTestCaseFilter {
            get {
                return ResourceManager.GetString("NoTestCaseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find process.
        /// </summary>
        public static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunSettingsDocument does not contain a RunSettings node! Canceling settings merging....
        /// </summary>
        public static string RunSettingsMissingNode {
            get {
                return ResourceManager.GetString("RunSettingsMissingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution settings: {0}.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution test settings file found at &apos;{0}&apos;, but does not contain {1} node.
        /// </summary>
        public static string SolutionFoundButMissingNode {
            get {
                return ResourceManager.GetString("SolutionFoundButMissingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test case filter: {0}.
        /// </summary>
        public static string TestCaseFilter {
            get {
                return ResourceManager.GetString("TestCaseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test discovery.
        /// </summary>
        public static string TestDiscovery {
            get {
                return ResourceManager.GetString("TestDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test discovery completed, overall duration: {0}.
        /// </summary>
        public static string TestDiscoveryCompleted {
            get {
                return ResourceManager.GetString("TestDiscoveryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while discovering tests: {0}.
        /// </summary>
        public static string TestDiscoveryExceptionError {
            get {
                return ResourceManager.GetString("TestDiscoveryExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test execution.
        /// </summary>
        public static string TestExecution {
            get {
                return ResourceManager.GetString("TestExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution canceled..
        /// </summary>
        public static string TestExecutionCancelled {
            get {
                return ResourceManager.GetString("TestExecutionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Test execution completed, overall duration: {0}.
        /// </summary>
        public static string TestExecutionCompleted {
            get {
                return ResourceManager.GetString("TestExecutionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while running tests: {0}.
        /// </summary>
        public static string TestRunningException {
            get {
                return ResourceManager.GetString("TestRunningException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait has same name as base test property and will thus be ignored for test case filtering: {0}.
        /// </summary>
        public static string TraitIgnoreMessage {
            get {
                return ResourceManager.GetString("TraitIgnoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown enum literal: {0}.
        /// </summary>
        public static string UnknownEnum {
            get {
                return ResourceManager.GetString("UnknownEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown enum literal: {0}.
        /// </summary>
        public static string UnknownLiteral {
            get {
                return ResourceManager.GetString("UnknownLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Visual Studio version: {0}.
        /// </summary>
        public static string UnknownVisualStudioVersion {
            get {
                return ResourceManager.GetString("UnknownVisualStudioVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires at least Visual Studio 2012 Update 1 - please update your Visual Studio installation..
        /// </summary>
        public static string VS2012Error {
            get {
                return ResourceManager.GetString("VS2012Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio version: {0}.
        /// </summary>
        public static string VSVersion {
            get {
                return ResourceManager.GetString("VSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find out Visual Studio version: {0}.
        /// </summary>
        public static string VSVersionMessage {
            get {
                return ResourceManager.GetString("VSVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0}.
        /// </summary>
        public static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
    }
}
